// SPDX-License-Identifier: Apache 2.0
// Copyright 2024 - Present, Light Transport Entertainment Inc.
//
// Visual regression test: renders test PDFs via ThorVG or Blend2D backend
// and compares output against reference images generated by pdftoppm.
//
// Build with either -DNANOPDF_USE_THORVG=ON or -DNANOPDF_USE_BLEND2D=ON.
// Reference images must be pre-generated via scripts/generate-visual-refs.sh.

#include <cmath>
#include <cstdint>
#include <cstring>
#include <fstream>
#include <iostream>
#include <string>
#include <vector>

#include <sys/stat.h>
#include <sys/types.h>

#include "nanopdf.hh"

#ifdef NANOPDF_USE_THORVG
#include "thorvg-backend.hh"
#endif

#ifdef NANOPDF_USE_BLEND2D
#include "blend2d-backend.hh"
#endif

// stb_image for loading reference PNGs
#include "stb_image.h"
// stb_image_write for saving rendered output and diffs
#include "stb_image_write.h"

namespace {

#ifdef NANOPDF_SOURCE_DIR
std::string source_dir() { return NANOPDF_SOURCE_DIR; }
#else
std::string source_dir() { return ".."; }
#endif

std::string data_dir() { return source_dir() + "/data"; }
std::string ref_dir() { return data_dir() + "/visual_refs"; }

// Test case definition
struct TestCase {
  std::string pdf_name;    // e.g. "blank.pdf"
  int threshold;           // per-channel diff threshold
  double max_diff_pct;     // max % of pixels exceeding threshold
};

// Comparison result
struct CompareResult {
  bool valid{false};
  double rmse{0.0};
  double psnr{0.0};
  int max_channel_diff{0};
  double diff_pct{0.0};
};

const float kDPI = 150.0f;

bool file_exists(const std::string& path) {
  struct stat st;
  return stat(path.c_str(), &st) == 0;
}

bool ensure_directory(const std::string& path) {
  struct stat st;
  if (stat(path.c_str(), &st) == 0) {
    return S_ISDIR(st.st_mode);
  }
  return mkdir(path.c_str(), 0755) == 0;
}

CompareResult compare_pixels(const uint8_t* actual, int aw, int ah,
                              int a_channels,
                              const uint8_t* ref, int rw, int rh,
                              int r_channels,
                              int threshold) {
  CompareResult result;

  // Allow small dimension differences (±2 pixels) due to DPI rounding.
  // Compare only the overlapping region.
  int dw = aw - rw;
  int dh = ah - rh;
  if (dw < 0) dw = -dw;
  if (dh < 0) dh = -dh;
  if (dw > 2 || dh > 2) {
    std::cerr << "    Dimension mismatch too large: rendered=" << aw << "x"
              << ah << " ref=" << rw << "x" << rh << std::endl;
    return result;
  }

  int cmp_w = (aw < rw) ? aw : rw;
  int cmp_h = (ah < rh) ? ah : rh;

  if (aw != rw || ah != rh) {
    std::cerr << "    Note: Dimensions differ slightly (rendered=" << aw << "x"
              << ah << " ref=" << rw << "x" << rh
              << "), comparing " << cmp_w << "x" << cmp_h << " overlap"
              << std::endl;
  }

  result.valid = true;
  size_t total_pixels = static_cast<size_t>(cmp_w) * cmp_h;
  double sum_sq = 0.0;
  size_t exceeding = 0;

  for (int y = 0; y < cmp_h; ++y) {
    for (int x = 0; x < cmp_w; ++x) {
      size_t a_idx = static_cast<size_t>(y * aw + x);
      size_t r_idx = static_cast<size_t>(y * rw + x);
      int pixel_max_diff = 0;
      for (int c = 0; c < 3; ++c) {
        int av = (c < a_channels)
                     ? static_cast<int>(actual[a_idx * a_channels + c])
                     : 0;
        int rv = (c < r_channels)
                     ? static_cast<int>(ref[r_idx * r_channels + c])
                     : 0;
        int diff = av - rv;
        if (diff < 0) diff = -diff;
        double ddiff = static_cast<double>(diff);
        sum_sq += ddiff * ddiff;
        if (diff > pixel_max_diff) pixel_max_diff = diff;
        if (diff > result.max_channel_diff) result.max_channel_diff = diff;
      }
      if (pixel_max_diff > threshold) {
        ++exceeding;
      }
    }
  }

  double mse = sum_sq / (total_pixels * 3);
  result.rmse = std::sqrt(mse);
  if (mse > 0.0) {
    result.psnr = 10.0 * std::log10(255.0 * 255.0 / mse);
  } else {
    result.psnr = 999.0;
  }
  result.diff_pct = 100.0 * static_cast<double>(exceeding) / total_pixels;
  return result;
}

void save_diff_image(const uint8_t* actual, int a_channels, int aw, int ah,
                     const uint8_t* ref, int r_channels, int rw, int rh,
                     const std::string& path) {
  int cmp_w = (aw < rw) ? aw : rw;
  int cmp_h = (ah < rh) ? ah : rh;
  std::vector<uint8_t> diff(static_cast<size_t>(cmp_w) * cmp_h * 3);

  for (int y = 0; y < cmp_h; ++y) {
    for (int x = 0; x < cmp_w; ++x) {
      size_t a_idx = static_cast<size_t>(y * aw + x);
      size_t r_idx = static_cast<size_t>(y * rw + x);
      size_t d_idx = static_cast<size_t>(y * cmp_w + x);
      for (int c = 0; c < 3; ++c) {
        int av = (c < a_channels) ? static_cast<int>(actual[a_idx * a_channels + c]) : 0;
        int rv = (c < r_channels) ? static_cast<int>(ref[r_idx * r_channels + c]) : 0;
        int d = av - rv;
        if (d < 0) d = -d;
        d *= 4;  // amplify for visibility
        if (d > 255) d = 255;
        diff[d_idx * 3 + c] = static_cast<uint8_t>(d);
      }
    }
  }

  stbi_write_png(path.c_str(), cmp_w, cmp_h, 3, diff.data(), cmp_w * 3);
}

#if defined(NANOPDF_USE_THORVG) || defined(NANOPDF_USE_BLEND2D)

struct RenderResult {
  bool success{false};
  std::string error;
  std::vector<uint8_t> pixels;  // RGB(A) data
  int width{0};
  int height{0};
  int channels{0};  // 4 for RGBA from backends
};

RenderResult render_pdf(const std::string& pdf_path) {
  RenderResult rr;

  // Load PDF
  std::ifstream ifs(pdf_path, std::ios::binary);
  if (!ifs) {
    rr.error = "Failed to open PDF: " + pdf_path;
    return rr;
  }
  std::vector<uint8_t> pdf_data((std::istreambuf_iterator<char>(ifs)),
                                std::istreambuf_iterator<char>());
  ifs.close();

  nanopdf::Pdf pdf;
  if (!nanopdf::parse_from_memory(pdf_data.data(), pdf_data.size(), &pdf)) {
    rr.error = "Failed to parse PDF";
    return rr;
  }

  if (!pdf.load_document_structure()) {
    rr.error = "Failed to load document structure";
    return rr;
  }

  if (pdf.catalog.pages.empty()) {
    rr.error = "No pages in PDF";
    return rr;
  }

  const auto& page = pdf.catalog.pages[0];

#ifdef NANOPDF_USE_THORVG
  nanopdf::ThorVGBackend backend;
  nanopdf::ThorVGRenderOptions opts;
  opts.dpi = kDPI;

  // Calculate pixel dimensions from page size at target DPI
  double page_width = 612.0, page_height = 792.0;
  if (page.media_box.size() >= 4) {
    page_width = page.media_box[2] - page.media_box[0];
    page_height = page.media_box[3] - page.media_box[1];
  }
  uint32_t w = static_cast<uint32_t>(page_width * kDPI / 72.0 + 0.5);
  uint32_t h = static_cast<uint32_t>(page_height * kDPI / 72.0 + 0.5);

  if (!backend.initialize(w, h)) {
    rr.error = "Failed to initialize ThorVG backend";
    return rr;
  }

  auto result = backend.render_page(pdf, page, opts);
  if (!result.success) {
    rr.error = "Render failed: " + result.error;
    return rr;
  }

  rr.success = true;
  rr.pixels = std::move(result.pixels);
  rr.width = static_cast<int>(result.width);
  rr.height = static_cast<int>(result.height);
  rr.channels = 4;  // RGBA

#elif defined(NANOPDF_USE_BLEND2D)
  nanopdf::Blend2DBackend backend;
  nanopdf::RenderOptions opts;
  opts.dpi = kDPI;

  double page_width = 612.0, page_height = 792.0;
  if (page.media_box.size() >= 4) {
    page_width = page.media_box[2] - page.media_box[0];
    page_height = page.media_box[3] - page.media_box[1];
  }
  uint32_t w = static_cast<uint32_t>(page_width * kDPI / 72.0 + 0.5);
  uint32_t h = static_cast<uint32_t>(page_height * kDPI / 72.0 + 0.5);

  if (!backend.initialize(w, h)) {
    rr.error = "Failed to initialize Blend2D backend";
    return rr;
  }

  auto result = backend.render_page(pdf, page, opts);
  if (!result.success) {
    rr.error = "Render failed: " + result.error;
    return rr;
  }

  rr.success = true;
  rr.pixels = std::move(result.pixels);
  rr.width = static_cast<int>(result.width);
  rr.height = static_cast<int>(result.height);
  rr.channels = 4;  // RGBA
#endif

  return rr;
}

#endif  // NANOPDF_USE_THORVG || NANOPDF_USE_BLEND2D

}  // namespace

int main(int argc, char** argv) {
#if !defined(NANOPDF_USE_THORVG) && !defined(NANOPDF_USE_BLEND2D)
  std::cerr << "No rendering backend enabled. Build with "
               "-DNANOPDF_USE_THORVG=ON or -DNANOPDF_USE_BLEND2D=ON"
            << std::endl;
  return 2;
#else

#ifdef NANOPDF_USE_THORVG
  const char* backend_name = "ThorVG";
#else
  const char* backend_name = "Blend2D";
#endif

  std::cout << "Visual Regression Test (" << backend_name << ")" << std::endl;
  std::cout << "========================================" << std::endl;

  // Define test cases with per-test tolerance
  std::vector<TestCase> tests = {
    {"blank.pdf",          2,  1.0},
    {"test_graphics.pdf",  5,  5.0},
    {"test_clip.pdf",      5,  5.0},
    {"test_dash.pdf",      5,  6.0},
    {"test_pattern.pdf",   5,  5.0},
    {"test_image.pdf",     8, 10.0},
    {"test_gradient.pdf",  8,  5.0},
    {"test_radial.pdf",    8,  5.0},
    {"test_multistop.pdf", 8,  5.0},
    {"test_textmode.pdf",  8, 10.0},
    {"test_textmode2.pdf", 8, 20.0},
  };

  // Override test list if specific PDFs are given on command line
  if (argc > 1) {
    tests.clear();
    for (int i = 1; i < argc; ++i) {
      // Extract just the filename from path
      std::string arg = argv[i];
      std::string name = arg;
      size_t pos = arg.rfind('/');
      if (pos != std::string::npos) {
        name = arg.substr(pos + 1);
      }
      tests.push_back({name, 8, 10.0});
    }
  }

  // Set up output directory for failure artifacts
  std::string output_dir = "visual_regression_output";
  ensure_directory(output_dir);

  int passed = 0;
  int failed = 0;
  int skipped = 0;

  for (const auto& tc : tests) {
    std::string pdf_path = data_dir() + "/" + tc.pdf_name;
    std::string stem = tc.pdf_name.substr(0, tc.pdf_name.size() - 4);
    std::string ref_path = ref_dir() + "/" + stem + "-page1-150dpi.png";

    std::cout << "\n--- " << tc.pdf_name << " ---" << std::endl;

    // Check if PDF exists
    if (!file_exists(pdf_path)) {
      std::cout << "  SKIP: PDF not found (" << pdf_path << ")" << std::endl;
      ++skipped;
      continue;
    }

    // Check if reference exists
    if (!file_exists(ref_path)) {
      std::cout << "  SKIP: Reference image not found (" << ref_path << ")"
                << std::endl;
      std::cout << "  Run: ./scripts/generate-visual-refs.sh" << std::endl;
      ++skipped;
      continue;
    }

    // Render PDF
    RenderResult rendered = render_pdf(pdf_path);
    if (!rendered.success) {
      std::cout << "  FAIL: " << rendered.error << std::endl;
      ++failed;
      continue;
    }

    // Load reference image
    int rw, rh, rc;
    uint8_t* ref_pixels = stbi_load(ref_path.c_str(), &rw, &rh, &rc, 0);
    if (!ref_pixels) {
      std::cout << "  FAIL: Cannot load reference: " << ref_path << std::endl;
      ++failed;
      continue;
    }

    // Compare
    CompareResult cmp = compare_pixels(
        rendered.pixels.data(), rendered.width, rendered.height,
        rendered.channels,
        ref_pixels, rw, rh, rc,
        tc.threshold);

    if (!cmp.valid) {
      std::cout << "  FAIL: Comparison failed" << std::endl;
      stbi_image_free(ref_pixels);
      ++failed;

      // Save rendered output for debugging
      std::string out_path = output_dir + "/" + stem + "-rendered.png";
      stbi_write_png(out_path.c_str(), rendered.width, rendered.height,
                     rendered.channels, rendered.pixels.data(),
                     rendered.width * rendered.channels);
      std::cout << "  Saved rendered: " << out_path << std::endl;
      continue;
    }

    std::cout << "  RMSE: " << cmp.rmse
              << "  PSNR: " << cmp.psnr << " dB"
              << "  MaxDiff: " << cmp.max_channel_diff
              << "  Exceeding: " << cmp.diff_pct << "% (limit "
              << tc.max_diff_pct << "%)" << std::endl;

    if (cmp.diff_pct > tc.max_diff_pct) {
      std::cout << "  FAIL: " << cmp.diff_pct << "% pixels exceed threshold "
                << tc.threshold << " (limit " << tc.max_diff_pct << "%)"
                << std::endl;
      ++failed;

      // Save artifacts for debugging
      std::string out_rendered = output_dir + "/" + stem + "-rendered.png";
      std::string out_diff = output_dir + "/" + stem + "-diff.png";

      stbi_write_png(out_rendered.c_str(), rendered.width, rendered.height,
                     rendered.channels, rendered.pixels.data(),
                     rendered.width * rendered.channels);
      save_diff_image(rendered.pixels.data(), rendered.channels,
                      rendered.width, rendered.height,
                      ref_pixels, rc, rw, rh,
                      out_diff);

      std::cout << "  Saved rendered: " << out_rendered << std::endl;
      std::cout << "  Saved diff:     " << out_diff << std::endl;
    } else {
      std::cout << "  PASS" << std::endl;
      ++passed;
    }

    stbi_image_free(ref_pixels);
  }

  std::cout << "\n========================================" << std::endl;
  std::cout << "Results: " << passed << " passed, " << failed << " failed, "
            << skipped << " skipped" << std::endl;

  return (failed > 0) ? 1 : 0;

#endif  // NANOPDF_USE_THORVG || NANOPDF_USE_BLEND2D
}
