#!/usr/bin/env python3
"""
embed_fonts.py - Generate C++ header with embedded font data (zlib compressed)
Usage: python3 embed_fonts.py <fonts_dir> <output_file> [options]

Options:
  --exclude-dirs=dir1,dir2       Skip fonts in these subdirectories
  --include-only-dirs=dir1,dir2  Only process fonts in these subdirectories
  --header-guard=NAME            Override header guard (default: NANOPDF_EMBEDDED_FONTS_HH)
  --namespace=NAME               Override namespace (default: embedded_fonts)
  --skip-pdf-mapping             Don't generate PDF Standard 14 mapping table
"""

import sys
import os
import glob
import zlib

def c_identifier(name):
    """Convert filename to a valid C identifier"""
    name = name.replace('-', '_').replace(' ', '_').replace('.', '_')
    return name.lower()

def parse_options(args):
    """Parse --flag=value options from command line args"""
    opts = {
        'exclude_dirs': [],
        'include_only_dirs': [],
        'header_guard': 'NANOPDF_EMBEDDED_FONTS_HH',
        'namespace': 'embedded_fonts',
        'skip_pdf_mapping': False,
    }
    for arg in args:
        if arg.startswith('--exclude-dirs='):
            opts['exclude_dirs'] = [d.strip() for d in arg.split('=', 1)[1].split(',') if d.strip()]
        elif arg.startswith('--include-only-dirs='):
            opts['include_only_dirs'] = [d.strip() for d in arg.split('=', 1)[1].split(',') if d.strip()]
        elif arg.startswith('--header-guard='):
            opts['header_guard'] = arg.split('=', 1)[1]
        elif arg.startswith('--namespace='):
            opts['namespace'] = arg.split('=', 1)[1]
        elif arg == '--skip-pdf-mapping':
            opts['skip_pdf_mapping'] = True
        else:
            print(f"Warning: Unknown option: {arg}", file=sys.stderr)
    return opts

def filter_font_files(font_files, fonts_dir, opts):
    """Filter font files by directory include/exclude lists"""
    if not opts['exclude_dirs'] and not opts['include_only_dirs']:
        return font_files

    filtered = []
    for font_file in font_files:
        # Get relative path from fonts_dir
        rel_path = os.path.relpath(font_file, fonts_dir)
        # Get the first directory component (subdirectory name)
        parts = rel_path.replace('\\', '/').split('/')
        subdir = parts[0] if len(parts) > 1 else ''

        if opts['include_only_dirs']:
            if subdir in opts['include_only_dirs']:
                filtered.append(font_file)
        elif opts['exclude_dirs']:
            if subdir not in opts['exclude_dirs']:
                filtered.append(font_file)
        else:
            filtered.append(font_file)

    return filtered

def generate_header(fonts_dir, output_file, opts=None):
    """Generate embedded fonts header file with zlib compression"""
    if opts is None:
        opts = parse_options([])

    header_guard = opts['header_guard']
    namespace = opts['namespace']
    skip_pdf_mapping = opts['skip_pdf_mapping']

    # Find all font files
    font_files = []
    for ext in ['*.ttf', '*.otf']:
        font_files.extend(glob.glob(os.path.join(fonts_dir, '**', ext), recursive=True))

    # Apply directory filtering
    font_files = filter_font_files(font_files, fonts_dir, opts)

    if not font_files:
        print(f"Error: No font files found in {fonts_dir} (after filtering)", file=sys.stderr)
        sys.exit(1)

    font_files.sort()

    # Open output file
    with open(output_file, 'w') as f:
        # Write header
        f.write("// Auto-generated file - DO NOT EDIT\n")
        f.write("// Generated by cmake/embed_fonts.py\n")
        f.write("// Contains embedded font data for PDF Standard 14 alternatives\n")
        f.write("// Font data is compressed with zlib to reduce binary size\n\n")
        f.write(f"#ifndef {header_guard}\n")
        f.write(f"#define {header_guard}\n\n")
        f.write("#include <cstddef>\n")
        f.write("#include <cstdint>\n")
        f.write("#include <cstring>\n")
        f.write("#include <vector>\n\n")

        # Add zlib include based on configuration
        f.write("// zlib decompression support\n")
        f.write("#ifdef NANOPDF_USE_MINIZ\n")
        f.write("#include \"miniz.h\"\n")
        f.write("#define NANOPDF_ZLIB_PREFIX(name) mz_##name\n")
        f.write("#else\n")
        f.write("#include <zlib.h>\n")
        f.write("#define NANOPDF_ZLIB_PREFIX(name) name\n")
        f.write("#endif\n\n")

        f.write("namespace nanopdf {\n")
        f.write(f"namespace {namespace} {{\n\n")

        font_entries = []
        total_original = 0
        total_compressed = 0

        # Process each font file
        for font_file in font_files:
            font_name = os.path.splitext(os.path.basename(font_file))[0]
            font_ext = os.path.splitext(font_file)[1]
            font_id = c_identifier(font_name)

            # Read font data
            with open(font_file, 'rb') as font_f:
                font_data = font_f.read()

            original_size = len(font_data)

            # Compress with zlib (level 9 for maximum compression)
            compressed_data = zlib.compress(font_data, level=9)
            compressed_size = len(compressed_data)

            compression_ratio = (1 - compressed_size / original_size) * 100

            print(f"Embedding font: {font_name}{font_ext} -> {font_id}")
            print(f"  Original: {original_size:,} bytes")
            print(f"  Compressed: {compressed_size:,} bytes ({compression_ratio:.1f}% reduction)")

            total_original += original_size
            total_compressed += compressed_size

            # Write compressed font data array
            f.write(f"// {font_name}{font_ext}\n")
            f.write(f"// Original: {original_size} bytes, Compressed: {compressed_size} bytes ({compression_ratio:.1f}% reduction)\n")
            f.write(f"static const unsigned char {font_id}_compressed_data[] = {{\n")

            # Write compressed bytes in lines of 16
            for i in range(0, len(compressed_data), 16):
                chunk = compressed_data[i:i+16]
                hex_bytes = ', '.join(f'0x{b:02x}' for b in chunk)
                f.write(f"  {hex_bytes}")
                if i + 16 < len(compressed_data):
                    f.write(",")
                f.write("\n")

            f.write("};\n\n")
            f.write(f"static const size_t {font_id}_compressed_size = {compressed_size};\n")
            f.write(f"static const size_t {font_id}_original_size = {original_size};\n")
            f.write(f"static const char* {font_id}_name = \"{font_name}{font_ext}\";\n\n")

            # Add to registry
            font_entries.append(
                f'  {{ "{font_name}", {font_id}_compressed_data, {font_id}_compressed_size, '
                f'{font_id}_original_size, "{font_name}{font_ext}" }}'
            )

        # Write statistics
        total_ratio = (1 - total_compressed / total_original) * 100
        f.write(f"// Compression statistics:\n")
        f.write(f"// Total original size: {total_original:,} bytes ({total_original/1024/1024:.2f} MB)\n")
        f.write(f"// Total compressed size: {total_compressed:,} bytes ({total_compressed/1024/1024:.2f} MB)\n")
        f.write(f"// Overall compression: {total_ratio:.1f}% size reduction\n\n")

        print(f"\nCompression Summary:")
        print(f"  Total original: {total_original:,} bytes ({total_original/1024/1024:.2f} MB)")
        print(f"  Total compressed: {total_compressed:,} bytes ({total_compressed/1024/1024:.2f} MB)")
        print(f"  Space saved: {total_original - total_compressed:,} bytes ({total_ratio:.1f}% reduction)")

        # Write font registry
        f.write("// Font registry\n")
        f.write("struct FontEntry {\n")
        f.write("  const char* base_name;              // Base name (e.g., \"Arimo-Regular\")\n")
        f.write("  const unsigned char* compressed_data; // Compressed font binary data\n")
        f.write("  size_t compressed_size;             // Compressed data size in bytes\n")
        f.write("  size_t original_size;               // Uncompressed data size in bytes\n")
        f.write("  const char* filename;               // Original filename\n")
        f.write("};\n\n")

        f.write("static const FontEntry font_registry[] = {\n")
        f.write(",\n".join(font_entries))
        f.write("\n};\n\n")

        f.write("static const size_t font_count = sizeof(font_registry) / sizeof(font_registry[0]);\n\n")

        # Write decompression helper
        f.write("// Helper function to decompress a font\n")
        f.write("// Returns true on success, false on error\n")
        f.write("inline bool decompress_font(const FontEntry* entry, std::vector<uint8_t>& output) {\n")
        f.write("  if (!entry || !entry->compressed_data) return false;\n")
        f.write("  \n")
        f.write("  output.resize(entry->original_size);\n")
        f.write("  \n")
        f.write("#ifdef NANOPDF_USE_MINIZ\n")
        f.write("  mz_ulong dest_len = entry->original_size;\n")
        f.write("  int result = mz_uncompress(\n")
        f.write("    output.data(),\n")
        f.write("    &dest_len,\n")
        f.write("    entry->compressed_data,\n")
        f.write("    entry->compressed_size\n")
        f.write("  );\n")
        f.write("  \n")
        f.write("  if (result != MZ_OK) {\n")
        f.write("    output.clear();\n")
        f.write("    return false;\n")
        f.write("  }\n")
        f.write("#else\n")
        f.write("  uLongf dest_len = entry->original_size;\n")
        f.write("  int result = uncompress(\n")
        f.write("    output.data(),\n")
        f.write("    &dest_len,\n")
        f.write("    entry->compressed_data,\n")
        f.write("    entry->compressed_size\n")
        f.write("  );\n")
        f.write("  \n")
        f.write("  if (result != Z_OK) {\n")
        f.write("    output.clear();\n")
        f.write("    return false;\n")
        f.write("  }\n")
        f.write("#endif\n")
        f.write("  \n")
        f.write("  return true;\n")
        f.write("}\n\n")

        # Write alternative decompress to raw pointer (for C-style APIs)
        f.write("// Helper function to decompress a font to a pre-allocated buffer\n")
        f.write("// buffer must be at least entry->original_size bytes\n")
        f.write("// Returns true on success, false on error\n")
        f.write("inline bool decompress_font_to_buffer(const FontEntry* entry, unsigned char* buffer, size_t buffer_size) {\n")
        f.write("  if (!entry || !entry->compressed_data || !buffer) return false;\n")
        f.write("  if (buffer_size < entry->original_size) return false;\n")
        f.write("  \n")
        f.write("#ifdef NANOPDF_USE_MINIZ\n")
        f.write("  mz_ulong dest_len = entry->original_size;\n")
        f.write("  int result = mz_uncompress(\n")
        f.write("    buffer,\n")
        f.write("    &dest_len,\n")
        f.write("    entry->compressed_data,\n")
        f.write("    entry->compressed_size\n")
        f.write("  );\n")
        f.write("  return result == MZ_OK;\n")
        f.write("#else\n")
        f.write("  uLongf dest_len = entry->original_size;\n")
        f.write("  int result = uncompress(\n")
        f.write("    buffer,\n")
        f.write("    &dest_len,\n")
        f.write("    entry->compressed_data,\n")
        f.write("    entry->compressed_size\n")
        f.write("  );\n")
        f.write("  return result == Z_OK;\n")
        f.write("#endif\n")
        f.write("}\n\n")

        # Write helper functions
        f.write("// Helper function to find a font by base name (case-insensitive)\n")
        f.write("inline const FontEntry* find_font(const char* name) {\n")
        f.write("  if (!name) return nullptr;\n")
        f.write("  \n")
        f.write("  for (size_t i = 0; i < font_count; ++i) {\n")
        f.write("    // Case-insensitive comparison\n")
        f.write("    const char* a = name;\n")
        f.write("    const char* b = font_registry[i].base_name;\n")
        f.write("    while (*a && *b) {\n")
        f.write("      char ca = (*a >= 'A' && *a <= 'Z') ? (*a + 32) : *a;\n")
        f.write("      char cb = (*b >= 'A' && *b <= 'Z') ? (*b + 32) : *b;\n")
        f.write("      if (ca != cb) break;\n")
        f.write("      ++a; ++b;\n")
        f.write("    }\n")
        f.write("    if (*a == *b) return &font_registry[i];\n")
        f.write("  }\n")
        f.write("  return nullptr;\n")
        f.write("}\n\n")

        if not skip_pdf_mapping:
            # Write PDF Standard 14 mapping
            f.write("// PDF Standard 14 font name mapping\n")
            f.write("struct FontMapping {\n")
            f.write("  const char* pdf_name;         // PDF Standard 14 name\n")
            f.write("  const char* substitute_name;  // Substitute font base name\n")
            f.write("};\n\n")

            f.write("static const FontMapping pdf_standard_14_mapping[] = {\n")
            f.write('  { "Helvetica",           "Arimo-Regular" },\n')
            f.write('  { "Helvetica-Bold",      "Arimo-Bold" },\n')
            f.write('  { "Helvetica-Oblique",   "Arimo-Italic" },\n')
            f.write('  { "Helvetica-BoldOblique", "Arimo-BoldItalic" },\n')
            f.write('  { "Times-Roman",         "Tinos-Regular" },\n')
            f.write('  { "Times-Bold",          "Tinos-Bold" },\n')
            f.write('  { "Times-Italic",        "Tinos-Italic" },\n')
            f.write('  { "Times-BoldItalic",    "Tinos-BoldItalic" },\n')
            f.write('  { "Courier",             "Cousine-Regular" },\n')
            f.write('  { "Courier-Bold",        "Cousine-Bold" },\n')
            f.write('  { "Courier-Oblique",     "Cousine-Italic" },\n')
            f.write('  { "Courier-BoldOblique", "Cousine-BoldItalic" },\n')
            f.write('  { "Symbol",              "STIXTwoMath-Regular" },\n')
            f.write('  { "ZapfDingbats",        "NotoSansSymbols-Regular" }\n')
            f.write("};\n\n")

            f.write("static const size_t pdf_mapping_count = sizeof(pdf_standard_14_mapping) / sizeof(pdf_standard_14_mapping[0]);\n\n")

            # Write helper to get PDF standard font
            f.write("// Get substitute font for a PDF Standard 14 font name\n")
            f.write("inline const FontEntry* get_pdf_standard_font(const char* pdf_name) {\n")
            f.write("  if (!pdf_name) return nullptr;\n")
            f.write("  \n")
            f.write("  for (size_t i = 0; i < pdf_mapping_count; ++i) {\n")
            f.write("    if (strcmp(pdf_name, pdf_standard_14_mapping[i].pdf_name) == 0) {\n")
            f.write("      return find_font(pdf_standard_14_mapping[i].substitute_name);\n")
            f.write("    }\n")
            f.write("  }\n")
            f.write("  return nullptr;\n")
            f.write("}\n\n")

        # Close namespaces and header guard
        f.write(f"}}  // namespace {namespace}\n")
        f.write("}  // namespace nanopdf\n\n")
        f.write(f"#endif  // {header_guard}\n")

    print(f"\nGenerated embedded fonts header: {output_file}")
    print(f"Total fonts embedded: {len(font_files)}")

if __name__ == '__main__':
    if len(sys.argv) < 3:
        print("Usage: python3 embed_fonts.py <fonts_dir> <output_file> [options]", file=sys.stderr)
        print("Options:", file=sys.stderr)
        print("  --exclude-dirs=dir1,dir2       Skip fonts in these subdirectories", file=sys.stderr)
        print("  --include-only-dirs=dir1,dir2  Only process fonts in these subdirectories", file=sys.stderr)
        print("  --header-guard=NAME            Override header guard", file=sys.stderr)
        print("  --namespace=NAME               Override namespace", file=sys.stderr)
        print("  --skip-pdf-mapping             Don't generate PDF Standard 14 mapping", file=sys.stderr)
        sys.exit(1)

    fonts_dir = sys.argv[1]
    output_file = sys.argv[2]
    opts = parse_options(sys.argv[3:])

    if not os.path.isdir(fonts_dir):
        print(f"Error: Directory not found: {fonts_dir}", file=sys.stderr)
        sys.exit(1)

    generate_header(fonts_dir, output_file, opts)
