SET(CMAKE_SYSTEM_NAME Windows)

IF (DEFINED ENV{LLVM_MINGW_DIR})
  SET(LLVM_MINGW_ROOT "$ENV{LLVM_MINGW_DIR}")
ELSE ()
  SET(LLVM_MINGW_ROOT "$ENV{HOME}/local/llvm-mingw-20251216-ucrt-ubuntu-22.04-x86_64")
ENDIF()

SET(CMAKE_C_COMPILER ${LLVM_MINGW_ROOT}/bin/i686-w64-mingw32-clang)
SET(CMAKE_CXX_COMPILER ${LLVM_MINGW_ROOT}/bin/i686-w64-mingw32-clang++)
SET(CMAKE_RC_COMPILER ${LLVM_MINGW_ROOT}/bin/i686-w64-mingw32-windres)

SET(CMAKE_FIND_ROOT_PATH ${LLVM_MINGW_ROOT}/i686-w64-mingw32)

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
